### ISSUE TITLE
Images for each recipe page do not load

### ISSUE THREAD

**Issue by avalon-zeta** [Jason-B-Jiang/Recipes-Website#1]
I stumbled on your submission from the recipes project page from TOP and noticed none of the images for each recipe load.

I was using this to quickly view your submission:
https://htmlpreview.github.io/?https://github.com/Jason-B-Jiang/Recipes-Website/blob/main/index.html

**Comment by avalon-zeta** [comment]
Apologies, just realized that tool only loads html as opposed to images. 

I tried your recipes site locally and it worked.

**Comment by Jason-B-Jiang** [comment]
Hey, no worries :)
